// <auto-generated />
namespace Air_Line_Flight.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nana : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nana));
        
        string IMigrationMetadata.Id
        {
            get { return "201610060136379_nana"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
